server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: angel
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: employee-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}