server:
  port: 8080
        
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        -id: schedule-service
        uri: lb://schedule-service
        predicates:
          - Path=/schedules/**

        -id: employee-service
        uri: lb://employee-service
        predicates:
          - Path=/employees/**  

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}